# Generated by Django 2.2.10 on 2020-03-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sherpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySMSHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_attempted', models.PositiveIntegerField()),
                ('total_delivered', models.PositiveIntegerField()),
                ('total_error', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Daily SMS history',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SMSResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed'), ('delivery_unconfirmed', 'Delivery Unconfirmed'), ('sending_failed', 'Sending Failed')], db_index=True, max_length=32)),
                ('sms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='sherpa.SMSMessage')),
            ],
        ),
    ]
