# Generated by Django 2.2.12 on 2020-05-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0041_auto_20200513_1951'),
        ('sms', '0002_premadetemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PremadeTemplate',
            new_name='CarrierApprovedTemplate',
        ),
    ]
