# Generated by Django 2.2.13 on 2020-09-15 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0119_company_allow_smart_stacker'),
        ('sms', '0004_carrierapprovedtemplate_alternate_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('is_custom', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_categories', to='sherpa.Company')),
            ],
            options={
                'unique_together': {('company', 'title')},
            },
        ),
    ]
