# Generated by Django 2.2.13 on 2020-09-16 15:18

from django.db import migrations, models

def create_opt_out_messages(apps, schema_editor):
    OptOutLanguage = apps.get_model('sms', 'OptOutLanguage')

    initial = [
        "If not, reply “stop”",
        "Not interested? Reply “stop”",
        "Simply reply “stop” if not interested in an offer",
        "If you’d rather not hear from me, reply “stop” to end",
        "If not, feel free to reply “stop”",
        "If you don’t want to chat, just reply “stop”",
        "You may reply “stop” to end, but",
        "Replying “stop” will end this convo",
        "Just reply “stop” if you don’t want to hear from us",
        "but you may reply “stop” if you’re not interested",
        "replying “stop” will end this thread",
        "reply “stop” to opt-out",
        "reply “stop” to end",
        "if you prefer, you may reply “stop”",
    ]

    for text in initial:
        OptOutLanguage.objects.create(text=text, is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_smstemplatecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptOutLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Available for selection in newly created or edited templates.')),
            ],
            options={'verbose_name_plural': 'Opt out language'},
        ),
        migrations.RunPython(create_opt_out_messages, migrations.RunPython.noop)
    ]
