# Generated by Django 2.2.13 on 2020-09-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_optoutlanguage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptOutLanguage',
        ),
    ]
