# Generated by Django 2.2.10 on 2020-03-07 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_phone_number_addons', models.PositiveSmallIntegerField()),
                ('actual_phone_number_addons', models.PositiveSmallIntegerField()),
                ('expected_market_addons', models.PositiveSmallIntegerField()),
                ('actual_market_addons', models.PositiveSmallIntegerField()),
                ('expected_subscription_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_subscription_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'discrepancies',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintree_id', models.CharField(max_length=16)),
                ('max_monthly_prospect_count', models.PositiveIntegerField()),
                ('max_phone_number_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('last_4', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_authorized', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dt_authorized', models.DateTimeField(blank=True, null=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('amount_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dt_charged', models.DateTimeField(blank=True, null=True)),
                ('is_charged', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_with_sync', models.BooleanField(default=False)),
            ],
        ),
    ]
