# Generated by Django 2.2.10 on 2020-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20200423_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('subscription fee', 'Subscription'), ('skip trace fee', 'Skip Trace'), ('credits fee', 'Sherpa Credits'), ('upload fee', 'Upload'), ('other', 'Other'), ('market', 'Market'), ('unknown', 'Unknown'), ('phone purchase', 'Phone Purchase')], max_length=16, null=True),
        ),
    ]
