# Generated by Django 2.2.12 on 2020-06-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20200502_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='display',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
