# Generated by Django 2.2.12 on 2020-06-08 16:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20200608_1412'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plan',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
    ]
