# Generated by Django 2.2.13 on 2020-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20200608_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancy',
            name='actual_subscription_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='discrepancy',
            name='expected_subscription_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
