# Generated by Django 2.2.13 on 2021-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20200629_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('subscription fee', 'Subscription'), ('skip trace fee', 'Skip Trace'), ('credits fee', 'Sherpa Credits'), ('upload fee', 'Upload'), ('other', 'Other'), ('market', 'Market'), ('unknown', 'Unknown'), ('phone purchase', 'Phone Purchase'), ('Direct mail fee', 'Direct mail fee')], max_length=16, null=True),
        ),
    ]
