# Generated by Django 2.2.10 on 2020-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_control_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('call_session_id', models.UUIDField(db_index=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('from_number', models.CharField(max_length=16)),
                ('to_number', models.CharField(max_length=16)),
                ('forwarded_number', models.CharField(blank=True, max_length=16)),
                ('error', models.CharField(blank=True, choices=[('no_sherpa_phone', 'No Sherpa Phone'), ('no_forwarding', 'No Forwarding Number'), ('error_forwarding', 'Error Forwarding'), ('no_prospect', 'No Prospect')], max_length=16)),
            ],
        ),
    ]
