# Generated by Django 2.2.10 on 2020-03-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('sherpa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sherpa.Prospect'),
        ),
        migrations.AddField(
            model_name='call',
            name='sherpa_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sherpa.PhoneNumber'),
        ),
    ]
