# Generated by Django 2.2.10 on 2020-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20200307_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='from_number',
            field=models.CharField(max_length=64),
        ),
    ]
