# Generated by Django 2.2.10 on 2020-04-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20200328_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='error',
            field=models.CharField(blank=True, choices=[('no_sherpa_phone', 'No Sherpa Phone'), ('no_forwarding', 'No Forwarding Number'), ('error_forwarding', 'Error Forwarding'), ('no_prospect', 'No Prospect'), ('api_error', 'Telnyx API Error')], max_length=16),
        ),
    ]
