# Generated by Django 2.2.13 on 2020-07-23 15:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0071_merge_20200721_1812'),
        ('calls', '0004_auto_20200408_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sherpa.UserProfile'),
        ),
        migrations.AddField(
            model_name='call',
            name='recording',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_control_id',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='call',
            name='error',
            field=models.CharField(blank=True, choices=[('no_sherpa_phone', 'No Sherpa Phone'), ('no_forwarding', 'No Forwarding Number'), ('error_forwarding', 'Error Forwarding'), ('no_prospect', 'No Prospect'), ('no_agent', 'No Agent'), ('api_error', 'Telnyx API Error')], max_length=16),
        ),
        migrations.AlterField(
            model_name='call',
            name='from_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
