# Generated by Django 2.2.13 on 2020-08-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20200731_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_type',
            field=models.CharField(blank=True, choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('click_to_call', 'Click to Call')], max_length=32, null=True),
        ),
    ]
