# Generated by Django 2.2.13 on 2020-08-12 18:31

import calls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_call_call_type'),
    ]

    operations = [
        migrations.RunSQL("UPDATE calls_call SET recording = NULL;"),
        migrations.AlterField(
            model_name='call',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to=calls.models.recording_path),
        ),
    ]
