# Generated by Django 2.2.24 on 2021-09-10 13:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.CharField(choices=[('att', 'AT&T'), ('t-mobile', 'T-Mobile'), ('verizon', 'Verizon')], max_length=50, primary_key=True, serialize=False)),
                ('carrier_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), db_index=True, help_text='Possible values returned when fetching carrier data (comma separated)', size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.CharField(choices=[('twilio', 'Twilio'), ('telnyx', 'Telnyx'), ('inteliquent', 'Inteliquent')], max_length=50, primary_key=True, serialize=False)),
                ('priority', models.PositiveIntegerField(unique=True)),
                ('managed', models.BooleanField()),
                ('sms_market_minimum', models.PositiveIntegerField()),
                ('new_market_number_count', models.PositiveIntegerField()),
                ('messages_per_phone_per_day', models.PositiveIntegerField()),
                ('opt_out_language', models.TextField()),
                ('excluded_carriers', models.ManyToManyField(blank=True, to='phone.Carrier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
