# Generated by Django 2.2.10 on 2020-03-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0012_auto_20200322_1221'),
        ('prospects', '0002_auto_20200307_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive'), ('released', 'Released')], db_index=True, default='active', max_length=16)),
                ('phone', models.CharField(db_index=True, max_length=16)),
                ('provider_id', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectRelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('agent_relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.UserProfile')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Prospect')),
                ('relay_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospects.RelayNumber')),
            ],
        ),
    ]
