# Generated by Django 2.2.10 on 2020-04-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_prospectrelay_relaynumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospectrelay',
            old_name='agent_relay',
            new_name='agent_profile',
        ),
    ]
