# Generated by Django 2.2.10 on 2020-04-06 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0004_auto_20200406_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectrelay',
            name='agent_profile',
            field=models.ForeignKey(help_text='Profile of the agent who is connected to the prospect.', on_delete=django.db.models.deletion.CASCADE, to='sherpa.UserProfile'),
        ),
    ]
