# Generated by Django 2.2.10 on 2020-04-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0005_auto_20200406_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecttag',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
