# Generated by Django 2.2.10 on 2020-04-30 20:58

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0006_prospecttag_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecttag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
