# Generated by Django 2.2.13 on 2020-07-17 13:25

from django.db import migrations, models


def set_order(apps, schema_editor):
    """
    Set an arbitrary order for each company's prospect tags, so that they can properly reorder.
    """
    Company = apps.get_model('sherpa', 'Company')
    companies = Company.objects.all()
    for company in companies:
        for index, prospect_tag in enumerate(company.prospecttag_set.all()):
            prospect_tag.order = index + 1
            prospect_tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0007_prospecttag_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospecttag',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='prospecttag',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(set_order, migrations.RunPython.noop)
    ]
