# Generated by Django 2.2.16 on 2020-09-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0009_auto_20200717_1815'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE sherpa_prospect_tags RENAME TO prospects_prospecttagassignment",
                    reverse_sql="ALTER TABLE prospects_prospecttagassignment RENAME TO sherpa_prospect_tags",
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ProspectTagAssignment',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Prospect')),
                        ('prospecttag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospects.ProspectTag')),
                    ],
                ),
            ]
        ),
        migrations.AddField(
            model_name='prospecttagassignment',
            name='assigned_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RenameField(
            model_name='prospecttagassignment',
            old_name='prospecttag',
            new_name='tag',
        )
    ]
