# Generated by Django 2.2.13 on 2020-09-21 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0010_prospecttagassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecttagassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
