# Generated by Django 2.2.13 on 2020-12-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0148_prospect_is_archived'),
        ('prospects', '0011_auto_20200921_1122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prospecttagassignment',
            unique_together={('tag', 'prospect')},
        ),
    ]
