# Generated by Django 2.2.13 on 2020-10-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skiptrace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skiptracedailystats',
            options={'ordering': ('-date',), 'verbose_name_plural': 'Skip trace daily stats'},
        ),
    ]
