# Generated by Django 2.2.23 on 2021-06-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0177_auto_20210526_1921'),
        ('properties', '0022_auto_20210608_0229'),
        ('skiptrace', '0002_auto_20201027_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSkipTracePropertyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyTag')),
                ('upload_skip_trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.UploadSkipTrace')),
            ],
            options={
                'unique_together': {('upload_skip_trace', 'property_tag')},
            },
        ),
    ]
