# Generated by Django 2.2.12 on 2020-06-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='ip_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
