CampaignProspectExportMap = {
    'Full Name': 'prospect..get_full_name()',
    'First Name': 'prospect.first_name',
    'Last Name': 'prospect.last_name',
    'Stage': 'prospect.lead_stage_title',
    'Phone': 'prospect.phone_display',
    'Mailing Street': 'prospect.mailing_address',
    'Mailing City': 'prospect.mailing_city',
    'Mailing State': 'prospect.mailing_state',
    'Mailing Zipcode': 'prospect.mailing_zip',
    'Property Street': 'prospect.property_address',
    'Property City': 'prospect.property_city',
    'Property State': 'prospect.property_state',
    'Property Zipcode': 'prospect.property_zip',
    'Phone Type': 'prospect.phone_type',
    'Custom 1': 'prospect.custom1',
    'First Import Date': 'prospect.created_date',
    'Last Import Date': 'prospect.last_import_date',
    'Owner Verified': 'prospect.owner_verified_status',
    'Is Vacant': 'prospect.validated_property_vacant',
    'Campaigns': 'prospect.campaign_names',
    'DNC': 'prospect.do_not_call',
    'Last SMS Sent': 'prospect.last_sms_sent_local',
    'Last SMS Received': 'prospect.last_sms_received_local',
    'Sherpa Page': 'sherpa_url',
    'Public Page': 'public_url',
    'Skip Reason': 'skip_reason',
    'Litigator': 'is_litigator',
    'Associated Litigator': 'is_associated_litigator',
}

SkipTraceExportMap = {
    'Full Name': 'submitted_owner_fullname',
    'First Name': 'submitted_owner_first_name',
    'Last Name': 'submitted_owner_last_name',
    'Mail Address': 'submitted_mailing_address',
    'Mail City': 'submitted_mailing_city',
    'Mail State': 'submitted_mailing_state',
    'Mail Zip': 'submitted_mailing_zip',
    'Property Address': 'submitted_property_address',
    'Property City': 'submitted_property_city',
    'Property State': 'submitted_property_state',
    'Property Zip': 'submitted_property_zip',
    'Custom 1': 'submitted_custom_1',
    'Custom 2': 'submitted_custom_2',
    'Custom 3': 'submitted_custom_3',
    'Custom 4': 'submitted_custom_4',
    'Custom 5': 'submitted_custom_5',
    'Custom 6': 'submitted_custom_6',
    'Validated Mail Address': 'validated_mailing_address_lines',
    'Validated Mail City': 'validated_mailing_city_name',
    'Validated Mail State': 'validated_mailing_state_abbreviation',
    'Validated Mail Zip': 'validated_mailing_zipcode',
    'Vacant': 'validated_mailing_vacant',
    'Alternate Full Name': 'proper_returned_fullname',
    'Alternate First Name': 'proper_returned_first_name',
    'Alternate Last Name': 'proper_returned_last_name',
    'Phone1': 'returned_phone_1',
    'Phone1 Type': 'returned_phone_type_1',
    'Phone1 Last Seen': 'returned_phone_last_seen_1',
    'Phone2': 'returned_phone_2',
    'Phone2 Type': 'returned_phone_type_2',
    'Phone2 Last Seen': 'returned_phone_last_seen_2',
    'Phone3': 'returned_phone_3',
    'Phone3 Type': 'returned_phone_type_3',
    'Phone3 Last Seen': 'returned_phone_last_seen_3',
    'Email1': 'proper_returned_email_1',
    'Email1 Last Seen': 'returned_email_last_seen_1',
    'Email2': 'proper_returned_email_2',
    'Email2 Last Seen': 'returned_email_last_seen_2',
    'IP Address': 'returned_ip_address',
    'IP Last Seen': 'returned_ip_last_seen',
    'Golden Address': 'golden_address_lines',
    'Golden City': 'golden_city',
    'Golden State': 'golden_state',
    'Golden Zip': 'golden_zipcode',
    'Golden Address Last Seen': 'golden_last_seen',
    'Age': 'age',
    'Is Deceased': 'deceased',
    'Bankruptcy': 'bankruptcy',
    'Foreclosure': 'returned_foreclosure_date',
    'Lien': 'returned_lien_date',
    'Judgment': 'returned_judgment_date',
    'Relative 1 First Name': 'proper_relative_1_first_name',
    'Relative 1 Last Name': 'proper_relative_1_last_name',
    'Relative 1 Phone1': 'relative_1_phone1',
    'Relative 1 Phone2': 'relative_1_phone2',
    'Relative 1 Phone3': 'relative_1_phone3',
    'Relative 2 First Name': 'proper_relative_2_first_name',
    'Relative 2 Last Name': 'proper_relative_2_last_name',
    'Relative 2 Phone1': 'relative_2_phone1',
    'Relative 2 Phone2': 'relative_2_phone2',
    'Relative 2 Phone3': 'relative_2_phone3',
    'Litigator': 'has_litigator',
    'Has Hit': 'has_hit',
    'Record Status': 'record_status',
}
