# Generated by Django 2.2.13 on 2020-09-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttomAddressData',
            fields=[
                ('attom_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('zip_code', models.CharField(blank=True, max_length=16, null=True)),
                ('attom', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.AttomAddressData')),
            ],
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address', 'city', 'state'], name='properties__address_6bc180_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('address', 'city', 'state')},
        ),
    ]
