# Generated by Django 2.2.13 on 2020-09-09 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0117_delete_incomingcall'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Company')),
                ('mailing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_properties', to='properties.Address')),
            ],
            options={
                'unique_together': {('company', 'address')},
            },
        ),
    ]
