# Generated by Django 2.2.13 on 2020-09-11 13:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0119_company_allow_smart_stacker'),
        ('properties', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_custom', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('distress_indicator', models.BooleanField(help_text='Determines if the tag is associated with linking a property to extra distress.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Company')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PropertyTagAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyTag')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(through='properties.PropertyTagAssignment', to='properties.PropertyTag'),
        ),
    ]
