# Generated by Django 2.2.13 on 2020-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_plus4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
