# Generated by Django 2.2.13 on 2020-09-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20200911_1344'),
        ('properties', '0003_address_zip_plus4'),
    ]

    operations = [
    ]
