# Generated by Django 2.2.13 on 2020-10-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20201026_1429'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attomassessor',
            table=None,
        ),
    ]
