# Generated by Django 2.2.13 on 2020-10-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20201026_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttomAmortizedLoanEquityModel',
            new_name='AttomAmortizedLoanEquity',
        ),
        migrations.RenameModel(
            old_name='AttomLoanModel',
            new_name='AttomLoan',
        ),
    ]
