# Generated by Django 2.2.13 on 2020-10-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20201026_1640'),
        ('properties', '0005_property_is_charged'),
    ]

    operations = [
    ]
