# Generated by Django 2.2.13 on 2020-10-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_merge_20201029_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attomassessor',
            name='parking_garage_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
