# Generated by Django 2.2.13 on 2020-11-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20201031_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
