# Generated by Django 2.2.13 on 2020-11-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_last_modified'),
        ('properties', '0011_auto_20201104_1848'),
    ]

    operations = [
    ]
