# Generated by Django 2.2.13 on 2020-11-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0143_auto_20201107_0103'),
        ('properties', '0012_merge_20201105_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='upload_skip_trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sherpa.UploadSkipTrace'),
        ),
    ]
