# Generated by Django 2.2.13 on 2020-11-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_upload_skip_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_archived',
            field=models.BooleanField(null=True),
        ),
    ]
