# Generated by Django 2.2.13 on 2020-11-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_is_archived'),
        ('properties', '0014_auto_20201125_2016'),
    ]

    operations = [
    ]
