# Generated by Django 2.2.13 on 2020-12-02 22:59

from django.db import migrations


def create_company_property_tags(apps, schema_editor):
    Company = apps.get_model('sherpa', 'Company')
    PropertyTag = apps.get_model('properties', 'PropertyTag')
    tags = [
        {'name': 'Absentee', 'distress_indicator': True},
        {'name': 'Bankruptcy', 'distress_indicator': True},
        {'name': 'Divorce', 'distress_indicator': True},
        {'name': 'Expired Listing', 'distress_indicator': True},
        {'name': 'Golden Address', 'distress_indicator': False},
        {'name': 'Judgement', 'distress_indicator': True},
        {'name': 'Lien', 'distress_indicator': True},
        {'name': 'Pre-foreclosure', 'distress_indicator': True},
        {'name': 'Probate / Death', 'distress_indicator': True},
        {'name': 'Vacant', 'distress_indicator': True},
        {'name': 'Tax default', 'distress_indicator': True},
        {'name': 'Quitclaim', 'distress_indicator': True},
    ]
    for company in Company.objects.all():
        for tag in tags:
            PropertyTag.objects.get_or_create(company=company, **tag)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_merge_20201127_0529'),
    ]

    operations = [
        migrations.RunPython(create_company_property_tags, migrations.RunPython.noop)
    ]
