# Generated by Django 2.2.13 on 2020-12-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20201202_2259'),
        ('properties', '0016_auto_20201204_2139'),
    ]

    operations = [
    ]
