# Generated by Django 2.2.13 on 2020-12-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0148_prospect_is_archived'),
        ('properties', '0017_merge_20201208_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='upload_prospects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sherpa.UploadProspects'),
        ),
    ]
