# Generated by Django 2.2.13 on 2021-01-20 15:31

from django.db import migrations


def create_high_equity_property_tags(apps, schema_editor):
    Company = apps.get_model('sherpa', 'Company')
    PropertyTag = apps.get_model('properties', 'PropertyTag')
    for company in Company.objects.all():
        PropertyTag.objects.get_or_create(
            company=company,
            name='High Equity',
            distress_indicator=False,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_upload_prospects'),
    ]

    operations = [
        migrations.RunPython(create_high_equity_property_tags, migrations.RunPython.noop)
    ]
