# Generated by Django 2.2.13 on 2021-05-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_addresslastvalidated'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=None, null=True),
        ),
    ]
