from rest_framework_csv.renderers import CSVRenderer


class SkipTracePropertyRenderer(CSVRenderer):
    header = [
        'Full Name',
        'First Name',
        'Last Name',
        'Mail Address',
        'Mail City',
        'Mail State',
        'Mail Zip',
        'Property Address',
        'Property City',
        'Property State',
        'Property Zip',
        'Custom 1',
        'Custom 2',
        'Custom 3',
        'Custom 4',
        'Custom 5',
        'Custom 6',
        'Validated Mail Address',
        'Validated Mail City',
        'Validated Mail State',
        'Validated Mail Zip',
        'Vacant',
        'Alternate Full Name',
        'Alternate First Name',
        'Alternate Last Name',
        'Phone1',
        'Phone1 Type',
        'Phone1 Last Seen',
        'Phone2',
        'Phone2 Type',
        'Phone2 Last Seen',
        'Phone3',
        'Phone3 Type',
        'Phone3 Last Seen',
        'Email1',
        'Email1 Last Seen',
        'Email2',
        'Email2 Last Seen',
        'IP Address',
        'IP Last Seen',
        'Golden Address',
        'Golden City',
        'Golden State',
        'Golden Zip',
        'Golden Address Last Seen',
        'Age',
        'Is Deceased',
        'Bankruptcy',
        'Foreclosure',
        'Lien',
        'Judgment',
        'Relative 1 First Name',
        'Relative 1 Last Name',
        'Relative 1 Phone1',
        'Relative 1 Phone2',
        'Relative 1 Phone3',
        'Relative 2 First Name',
        'Relative 2 Last Name',
        'Relative 2 Phone1',
        'Relative 2 Phone2',
        'Relative 2 Phone3',
        'Litigator',
        'Has Hit',
        'Record Status',
    ]
