# Generated by Django 2.2.10 on 2020-03-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sherpa', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygoal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Company'),
        ),
        migrations.AddField(
            model_name='companychurn',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='churn', to='sherpa.Company'),
        ),
    ]
