# Generated by Django 2.2.10 on 2020-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200307_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companychurn',
            name='prospect_upload_percent',
            field=models.SmallIntegerField(null=True),
        ),
    ]
