# Generated by Django 2.2.12 on 2020-06-04 15:45

import companies.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sherpa', '0051_merge_20200602_1416'),
        ('companies', '0003_auto_20200408_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('auto_stop', 'Auto Stop'), ('complete', 'Complete'), ('error', 'Error'), ('paused', 'Paused'), ('running', 'Running'), ('sent_to_task', 'Sent to Task'), ('setup', 'Setup')], default='setup', max_length=16)),
                ('last_row_processed', models.IntegerField(default=0)),
                ('total_rows', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('download_type', models.CharField(choices=[('campaign_prospect', 'CampaignProspect Export'), ('prospect', 'Prospect Export'), ('skiptrace', 'Skip Trace')], max_length=32)),
                ('file', models.FileField(upload_to=companies.models.download_path)),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('is_bulk', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sherpa.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
