# Generated by Django 2.2.12 on 2020-06-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_downloadhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadhistory',
            options={'verbose_name_plural': 'Download history'},
        ),
    ]
