# Generated by Django 2.2.12 on 2020-06-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200611_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadhistory',
            name='download_type',
            field=models.CharField(choices=[('campaign_prospect', 'CampaignProspect Export'), ('prospect', 'Prospect Export'), ('skiptrace', 'Skip Trace'), ('dnc', 'DNC')], max_length=32),
        ),
    ]
