# Generated by Django 2.2.12 on 2020-07-07 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0065_company_monthly_upload_count'),
        ('companies', '0006_auto_20200611_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_billing_date', models.DateField()),
                ('end_billing_date', models.DateField()),
                ('upload_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Company')),
            ],
            options={
                'verbose_name_plural': 'Monthly Upload Usage',
                'ordering': ('company', '-end_billing_date'),
            },
        ),
    ]
