# Generated by Django 2.2.13 on 2020-07-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0066_auto_20200708_1828'),
        ('companies', '0007_companyuploadhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyuploadhistory',
            unique_together={('company', 'start_billing_date')},
        ),
    ]
