# Generated by Django 2.2.13 on 2020-08-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20200709_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadhistory',
            name='download_type',
            field=models.CharField(choices=[('campaign_prospect', 'CampaignProspect Export'), ('prospect', 'Prospect Export'), ('skiptrace', 'Skip Trace'), ('dnc', 'DNC'), ('campaign', 'Campaign Export')], max_length=32),
        ),
    ]
