# Generated by Django 2.2.16 on 2020-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20200811_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadhistory',
            name='download_type',
            field=models.CharField(choices=[('campaign_prospect', 'CampaignProspect Export'), ('prospect', 'Prospect Export'), ('skiptrace', 'Skip Trace'), ('dnc', 'DNC'), ('campaign', 'Campaign Export'), ('campaign_meta_stats', 'CampaignMetaStats Export'), ('profile_stats', 'ProfileStats Export')], max_length=32),
        ),
    ]
