# Generated by Django 2.2.13 on 2020-11-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20200915_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadhistory',
            name='download_type',
            field=models.CharField(choices=[('campaign_prospect', 'CampaignProspect Export'), ('prospect', 'Prospect Export'), ('skiptrace', 'Skip Trace'), ('dnc', 'DNC'), ('campaign', 'Campaign Export'), ('campaign_meta_stats', 'CampaignMetaStats Export'), ('profile_stats', 'ProfileStats Export'), ('property', 'Property Export')], max_length=32),
        ),
    ]
