# Generated by Django 2.2.13 on 2020-12-29 01:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0149_auto_20201216_2055'),
        ('companies', '0011_auto_20201103_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephonyConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
                ('api_secret', models.TextField()),
                ('random_key', models.UUIDField(default=uuid.UUID('683a4962-bda4-4f91-a33a-20bb3c0f51c1'), editable=False)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('telnyx', 'Telnyx')], default='twilio', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Company')),
            ],
            options={
                'unique_together': {('company', 'provider')},
            },
        ),
    ]
