# Generated by Django 2.2.13 on 2020-12-03 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0148_prospect_is_archived'),
        ('companies', '0013_auto_20210112_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPodioCrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.PositiveIntegerField(null=True)),
                ('workspace', models.PositiveIntegerField(null=True)),
                ('application', models.PositiveIntegerField(null=True)),
                ('access_token', models.CharField(max_length=64, null=True)),
                ('refresh_token', models.CharField(max_length=64, null=True)),
                ('expires_in_token', models.PositiveIntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Company')),
            ],
        ),
    ]
