# Generated by Django 2.2.13 on 2020-12-28 19:31

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_companypodiocrm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodioFieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Company')),
            ],
        ),
    ]
