# Generated by Django 2.2.13 on 2020-12-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_podiofieldmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodioProspectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField()),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Prospect')),
            ],
        ),
    ]
