# Generated by Django 2.2.13 on 2021-01-18 20:30

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_podioprospectitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podiofieldmapping',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
