# Generated by Django 2.2.13 on 2021-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20210118_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypodiocrm',
            name='application',
            field=models.PositiveIntegerField(help_text='Podio Application id', null=True),
        ),
        migrations.AlterField(
            model_name='companypodiocrm',
            name='organization',
            field=models.PositiveIntegerField(help_text='Podio Organization id', null=True),
        ),
        migrations.AlterField(
            model_name='companypodiocrm',
            name='workspace',
            field=models.PositiveIntegerField(help_text='Podio Workspace id', null=True),
        ),
        migrations.AlterField(
            model_name='downloadhistory',
            name='status',
            field=models.CharField(choices=[('auto_stop', 'Auto Stop'), ('complete', 'Complete'), ('error', 'Error'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('running', 'Running'), ('sent_to_task', 'Sent to Task'), ('setup', 'Setup')], default='setup', max_length=16),
        ),
    ]
