# Generated by Django 2.2.13 on 2021-04-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20210223_1419'),
    ]
