# Generated by Django 2.2.13 on 2021-04-30 09:29

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0175_merge_20210429_1434'),
        ('companies', '0017_auto_20210416_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPropStackFilterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=120)),
                ('filter_json', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Company')),
            ],
        ),
    ]
