# Generated by Django 2.2.13 on 2021-05-18 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0175_merge_20210429_1434'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0018_companypropstackfiltersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypropstackfiltersettings',
            options={'verbose_name_plural': 'Company stacker filters'},
        ),
        migrations.AddField(
            model_name='companypropstackfiltersettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companypropstackfiltersettings',
            name='created_by',
            field=models.ForeignKey(default=102, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companypropstackfiltersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='companypropstackfiltersettings',
            unique_together={('company', 'filter_name')},
        ),
    ]
