# Generated by Django 2.2.24 on 2021-07-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20210518_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonyconnection',
            name='provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('telnyx', 'Telnyx'), ('inteliquent', 'Inteliquent')], default='twilio', max_length=16),
        ),
    ]
