# Generated by Django 2.2.10 on 2020-03-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20200307_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDeadDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('marked_auto_dead', models.BooleanField()),
                ('score', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
