# Generated by Django 2.2.10 on 2020-04-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_autodeaddetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignfolder',
            name='is_active',
        ),
    ]
