# Generated by Django 2.2.13 on 2020-08-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0087_remove_campaign_folder'),
        ('campaigns', '0005_campaigndailystats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignFolder',
        ),
    ]
