# Generated by Django 2.2.13 on 2020-09-11 13:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_delete_campaignfolder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigntag',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='campaigntag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigntag',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaigntag',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
