# Generated by Django 2.2.13 on 2021-03-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_auto_20210120_1531'),
        ('sherpa', '0154_company_enable_direct_mail_integration'),
        ('campaigns', '0008_campaignaggregatedstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('processing', 'processing'), ('complete', 'complete'), ('failed', 'failed')], max_length=255, null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(auto_now_add=True)),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectMailReturnAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Address')),
            ],
        ),
        migrations.CreateModel(
            name='DirectMailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yellowletter', 'Yellow Letter')], max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directmail', to='sherpa.Campaign')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.DirectMailOrder')),
                ('return_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.DirectMailReturnAddress')),
            ],
        ),
    ]
