# Generated by Django 2.2.13 on 2021-03-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_directmailcampaign_directmailorder_directmailreturnaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmailcampaign',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directmailcampaign',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
