# Generated by Django 2.2.13 on 2021-03-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20210309_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmailorder',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'processing'), ('complete', 'complete'), ('failed', 'failed'), ('locked', 'locked')], max_length=255, null=True),
        ),
    ]
