# Generated by Django 2.2.13 on 2021-03-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20210311_0921'),
        ('campaigns', '0011_auto_20210311_0851'),
    ]

    operations = [
    ]
