# Generated by Django 2.2.13 on 2021-03-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_merge_20210311_1952'),
        ('campaigns', '0012_auto_20210311_1400'),
    ]

    operations = [
    ]
