# Generated by Django 2.2.13 on 2021-03-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_merge_20210312_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmailorder',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directmailorder',
            name='in_production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directmailorder',
            name='in_transit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directmailorder',
            name='processed_for_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directmailorder',
            name='received_by_print_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
