# Generated by Django 2.2.13 on 2021-03-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_auto_20210316_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmailorder',
            old_name='target_date',
            new_name='drop_date',
        ),
    ]
