# Generated by Django 2.2.13 on 2021-03-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_auto_20210316_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmailcampaign',
            name='budget_per_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='directmailorder',
            name='creative_type',
            field=models.CharField(default='postcard', max_length=100),
        ),
        migrations.AddField(
            model_name='directmailorder',
            name='note_for_processor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
