# Generated by Django 2.2.13 on 2021-03-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_directmailreturnaddress_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmailorder',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'scheduled'), ('processing', 'processing'), ('complete', 'complete'), ('out_for_delivery', 'out_for_delivery'), ('failed', 'failed'), ('locked', 'locked'), ('incomplete', 'incomplete')], default='scheduled', max_length=255, null=True),
        ),
    ]
