# Generated by Django 2.2.13 on 2021-03-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_directmailreturnaddress_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmailcampaign',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
