# Generated by Django 2.2.13 on 2021-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_auto_20210324_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmailorder',
            name='tracking_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directmailorder',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'scheduled'), ('processing', 'processing'), ('complete', 'complete'), ('out_for_delivery', 'out_for_delivery'), ('failed', 'failed'), ('locked', 'locked'), ('incomplete', 'incomplete'), ('cancelled', 'cancelled')], default='scheduled', max_length=255, null=True),
        ),
    ]
