# Generated by Django 2.2.13 on 2021-03-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_directmailcampaign_is_draft'),
        ('campaigns', '0019_auto_20210326_1622'),
    ]

    operations = [
    ]
