# Generated by Django 2.2.13 on 2021-03-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_merge_20210330_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmailorder',
            name='tracking_job_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
