# Generated by Django 2.2.13 on 2021-04-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_directmailorder_tracking_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMailTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_count', models.IntegerField(default=0)),
                ('not_scanned', models.IntegerField(default=0)),
                ('early', models.IntegerField(default=0)),
                ('on_time', models.IntegerField(default=0)),
                ('late', models.IntegerField(default=0)),
                ('en_route', models.IntegerField(default=0)),
                ('total_undelivered', models.IntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='directmailorder',
            name='tracking_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.DirectMailTracking'),
        ),
    ]
