# Generated by Django 2.2.13 on 2021-04-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_auto_20210409_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmailcampaign',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directmail', to='sherpa.Campaign'),
        ),
    ]
