# Generated by Django 2.2.13 on 2021-04-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_auto_20210416_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMailTrackingByPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_imb', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('returned', 'Returned'), ('redirected', 'Redirected'), ('delivered', 'Delivered')], max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.DirectMailOrder')),
            ],
        ),
    ]
