# Generated by Django 2.2.10 on 2020-03-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='total_phone_lookup_count',
        ),
    ]
