# Generated by Django 2.2.10 on 2020-03-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0002_remove_campaign_total_phone_lookup_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_dead_enabled',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
