# Generated by Django 2.2.10 on 2020-03-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0003_company_auto_dead_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadprospects',
            name='exceeds_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
