# Generated by Django 2.2.10 on 2020-03-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0004_uploadprospects_exceeds_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadprospects',
            name='created_local',
        ),
    ]
