# Generated by Django 2.2.10 on 2020-03-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0005_remove_uploadprospects_created_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='total_active_twilio_phone_maintanance',
        ),
        migrations.RemoveField(
            model_name='market',
            name='twilio_phone_budget',
        ),
        migrations.AddField(
            model_name='market',
            name='included_phones',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
