# Generated by Django 2.2.10 on 2020-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0007_auto_20200316_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_billing_zip',
            field=models.BooleanField(default=False),
        ),
    ]
