# Generated by Django 2.2.10 on 2020-03-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0008_company_has_billing_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive'), ('released', 'Released')], db_index=True, default='active', max_length=16),
        ),
    ]
