# Generated by Django 2.2.10 on 2020-03-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0009_auto_20200317_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='disclaimer_signature_backup',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='disclaimer_timestamp_backup',
        ),
    ]
