# Generated by Django 2.2.10 on 2020-03-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0011_company_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadskiptrace',
            options={'ordering': ('id',)},
        ),
    ]
