# Generated by Django 2.2.10 on 2020-03-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0013_userprofile_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='block_unknown_calls',
            field=models.BooleanField(default=True),
        ),
    ]
