# Generated by Django 2.2.10 on 2020-04-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0016_auto_20200331_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statsbatch',
            options={'ordering': ('-created_utc',)},
        ),
    ]
