# Generated by Django 2.2.10 on 2020-04-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0018_prospect_cloned_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='twilio_account_sid',
        ),
        migrations.RemoveField(
            model_name='company',
            name='twilio_auth_token',
        ),
    ]
