# Generated by Django 2.2.10 on 2020-04-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0019_auto_20200402_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-date_utc',), 'verbose_name_plural': 'activities'},
        ),
    ]
