# Generated by Django 2.2.10 on 2020-04-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0020_auto_20200404_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadskiptrace',
            name='created_local',
        ),
    ]
