# Generated by Django 2.2.10 on 2020-04-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0022_auto_20200408_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSResponseNoProspectFound',
        ),
    ]
