# Generated by Django 2.2.10 on 2020-04-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0023_delete_smsresponsenoprospectfound'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadskiptrace',
            options={'ordering': ('-id',)},
        ),
    ]
