# Generated by Django 2.2.10 on 2020-04-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0024_auto_20200408_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='sherpa.Company'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='sherpa.Market'),
        ),
    ]
