# Generated by Django 2.2.10 on 2020-04-09 14:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sherpa', '0025_auto_20200409_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=64)),
                ('template', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('from_email', models.EmailField(default='Local Sherpa <sherpa@leadsherpa.com>', max_length=254)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
