# Generated by Django 2.2.10 on 2020-04-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0026_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadstage',
            unique_together={('company', 'lead_stage_title')},
        ),
    ]
