# Generated by Django 2.2.10 on 2020-04-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0027_auto_20200413_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
