# Generated by Django 2.2.10 on 2020-04-16 16:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_premadetemplate'),
        ('sherpa', '0028_delete_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignprospect',
            name='sms_premade_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.PremadeTemplate'),
        ),
        migrations.AddField(
            model_name='company',
            name='outgoing_company_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='Comma seperated list of company names to use in Premade SMS templates.', size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='outgoing_user_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, help_text='Comma seperated list of first names to use in Premade SMS templates.', size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='send_premade_templates',
            field=models.BooleanField(default=False, help_text='Allow campaigns to use premade (carrier verified) SMS templates'),
        ),
        migrations.AddField(
            model_name='statsbatch',
            name='skipped_outgoing_not_set',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignprospect',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('threshold', 'Threshold'), ('has_responded', 'Has responded previously'), ('company_dnc', 'Company DNC'), ('public_dnc', 'Public DNC'), ('litigator', 'Litigator'), ('has_receipt', 'Has SMS Receipt'), ('forced', 'Forced'), ('opt_out_required', 'Opt-out required'), ('carrier_att', 'AT&T'), ('outgoing_not_set', 'Outgoing not set')], max_length=16),
        ),
    ]
