# Generated by Django 2.2.10 on 2020-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0029_auto_20200416_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstage',
            name='lead_stage_title',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
