# Generated by Django 2.2.10 on 2020-04-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0031_company_is_billing_exempt'),
        ('sherpa', '0031_auto_20200420_1924'),
    ]

    operations = [
    ]
