# Generated by Django 2.2.10 on 2020-04-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0033_auto_20200422_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.CampaignFolder'),
        ),
    ]
