# Generated by Django 2.2.10 on 2020-04-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0034_auto_20200424_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invitation_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sherpa.InvitationCode'),
        ),
    ]
