# Generated by Django 2.2.10 on 2020-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0035_auto_20200424_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadstage',
            options={'ordering': ('lead_stage_number',)},
        ),
        migrations.AddField(
            model_name='leadstage',
            name='description',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
