# Generated by Django 2.2.10 on 2020-05-05 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0036_auto_20200501_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Business ending time.'),
        ),
        migrations.AddField(
            model_name='company',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Business starting time.'),
        ),
    ]
