# Generated by Django 2.2.10 on 2020-05-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0037_auto_20200505_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
