# Generated by Django 2.2.12 on 2020-05-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0038_auto_20200508_1904'),
        ('sherpa', '0038_auto_20200511_1835'),
    ]

    operations = [
    ]
