# Generated by Django 2.2.12 on 2020-05-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0039_merge_20200512_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
