# Generated by Django 2.2.12 on 2020-05-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0040_auto_20200513_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignprospect',
            old_name='sms_premade_template',
            new_name='sms_carrier_approved_template',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='send_premade_templates',
            new_name='send_carrier_approved_templates',
        ),
    ]
