# Generated by Django 2.2.12 on 2020-05-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0042_auto_20200515_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skiptraceproperty',
            options={'ordering': ['pk'], 'verbose_name_plural': 'skip trace properties'},
        ),
    ]
