# Generated by Django 2.2.12 on 2020-05-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0042_auto_20200515_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignprospect',
            name='podio_url',
        ),
    ]
