# Generated by Django 2.2.12 on 2020-05-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0042_auto_20200515_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadprospects',
            name='custom_2_column_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadprospects',
            name='custom_3_column_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadprospects',
            name='custom_4_column_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
