# Generated by Django 2.2.12 on 2020-05-21 22:03

from django.db import migrations
from django.db.models import Q


def update_blank_messages(apps, schema_editor):
    SMSTemplate = apps.get_model('sherpa', 'SMSTemplate')

    # Update empty message to '.'.
    SMSTemplate.objects.filter(Q(message__isnull=True) | Q(message__iexact='')).update(
        is_active=False,
        message='.',
    )

    # Update alternate alternate_message to '.'.
    SMSTemplate.objects.filter(
        Q(alternate_message__isnull=True) | Q(alternate_message__iexact='')
    ).update(is_active=False, alternate_message='.')


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0042_auto_20200515_1539'),
    ]

    operations = [
        migrations.RunPython(update_blank_messages, migrations.RunPython.noop)
    ]
