# Generated by Django 2.2.12 on 2020-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0043_auto_20200521_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='alternate_message',
            field=models.CharField(default='.', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='message',
            field=models.CharField(default='.', max_length=300),
            preserve_default=False,
        ),
    ]
