# Generated by Django 2.2.12 on 2020-05-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0043_remove_campaignprospect_podio_url'),
        ('sherpa', '0044_auto_20200522_1352'),
        ('sherpa', '0043_auto_20200522_1942'),
        ('sherpa', '0043_auto_20200521_2107'),
    ]

    operations = [
    ]
