# Generated by Django 2.2.12 on 2020-05-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0044_auto_20200523_1101'),
        ('sherpa', '0046_auto_20200523_1059'),
    ]

    operations = [
    ]
