# Generated by Django 2.2.12 on 2020-05-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0047_merge_20200526_1150'),
        ('sherpa', '0045_campaign_retain_numbers'),
    ]

    operations = [
    ]
