# Generated by Django 2.2.12 on 2020-05-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0048_merge_20200526_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='podio_app_id',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='podio_app_token',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='podio_lead_id',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='podio_url',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='saved_to_podio',
        ),
    ]
