# Generated by Django 2.2.12 on 2020-05-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0049_auto_20200528_1942'),
        ('sherpa', '0049_auto_20200528_1101'),
    ]

    operations = [
    ]
