# Generated by Django 2.2.12 on 2020-06-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0050_company_uuid'),
        ('sherpa', '0050_merge_20200529_1339'),
    ]

    operations = [
    ]
