# Generated by Django 2.2.12 on 2020-06-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0050_merge_20200529_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignprospect',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
