# Generated by Django 2.2.12 on 2020-06-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0051_merge_20200602_1416'),
        ('sherpa', '0051_auto_20200610_1259'),
    ]

    operations = [
    ]
