# Generated by Django 2.2.12 on 2020-06-12 15:54

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0052_merge_20200610_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadinternaldnc',
            name='file',
            field=models.FileField(null=True, upload_to=companies.models.upload_path),
        ),
        migrations.AddField(
            model_name='uploadlitigatorcheck',
            name='file',
            field=models.FileField(null=True, upload_to=companies.models.upload_path),
        ),
        migrations.AddField(
            model_name='uploadlitigatorlist',
            name='file',
            field=models.FileField(null=True, upload_to=companies.models.upload_path),
        ),
        migrations.AddField(
            model_name='uploadprospects',
            name='file',
            field=models.FileField(null=True, upload_to=companies.models.upload_path),
        ),
        migrations.AddField(
            model_name='uploadskiptrace',
            name='file',
            field=models.FileField(null=True, upload_to=companies.models.upload_path),
        ),
    ]
