# Generated by Django 2.2.13 on 2020-06-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0055_invitationcode_allow_starter'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsbatch',
            name='skipped_force',
            field=models.IntegerField(default=0),
        ),
    ]
