# Generated by Django 2.2.13 on 2020-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0056_statsbatch_skipped_force'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='skip_prospects_who_messaged',
            field=models.BooleanField(default=True),
        ),
    ]
