# Generated by Django 2.2.13 on 2020-06-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0057_campaign_skip_prospects_who_messaged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadstage',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='leadstage',
            old_name='lead_stage_number',
            new_name='order',
        ),
    ]
