# Generated by Django 2.2.13 on 2020-06-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0058_prospect_is_blocked'),
        ('sherpa', '0058_auto_20200624_1343'),
    ]

    operations = [
    ]
