# Generated by Django 2.2.13 on 2020-06-25 12:54

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0059_merge_20200625_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadinternaldnc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=companies.models.upload_path),
        ),
        migrations.AlterField(
            model_name='uploadlitigatorcheck',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=companies.models.upload_path),
        ),
        migrations.AlterField(
            model_name='uploadlitigatorlist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=companies.models.upload_path),
        ),
        migrations.AlterField(
            model_name='uploadprospects',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=companies.models.upload_path),
        ),
        migrations.AlterField(
            model_name='uploadskiptrace',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=companies.models.upload_path),
        ),
    ]
