# Generated by Django 2.2.13 on 2020-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0061_auto_20200627_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignprospect',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
