# Generated by Django 2.2.13 on 2020-06-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0062_auto_20200628_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_verify_prospects',
            field=models.BooleanField(default=False, help_text='When enabled, will auto-verify prospects during campaign import process.'),
        ),
    ]
