# Generated by Django 2.2.13 on 2020-07-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0063_company_auto_verify_prospects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areacodestate',
            options={'ordering': ('state', 'city')},
        ),
    ]
