# Generated by Django 2.2.12 on 2020-07-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0064_auto_20200702_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='opted_out',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
