# Generated by Django 2.2.12 on 2020-07-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0064_auto_20200702_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='monthly_upload_count',
            field=models.IntegerField(default=0),
        ),
    ]
