# Generated by Django 2.2.13 on 2020-07-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0065_company_monthly_upload_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
