# Generated by Django 2.2.13 on 2020-07-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0065_prospect_opted_out'),
        ('sherpa', '0066_auto_20200708_1828'),
    ]

    operations = [
    ]
