# Generated by Django 2.2.12 on 2020-07-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0068_prospect_reminder_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='delivery_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
