# Generated by Django 2.2.13 on 2020-07-17 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0068_prospect_reminder_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstage',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
