# Generated by Django 2.2.13 on 2020-07-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0069_auto_20200717_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_zapier_webhook',
            field=models.ForeignKey(blank=True, help_text='Companies default Zapier webhook implementation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_zapier_webhook', to='sherpa.ZapierWebhook'),
        ),
    ]
