# Generated by Django 2.2.13 on 2020-07-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0069_phonenumber_delivery_percentage'),
        ('sherpa', '0070_company_default_zapier_webhook'),
    ]

    operations = [
    ]
