# Generated by Django 2.2.13 on 2020-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0071_merge_20200721_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='sherpa_delivery_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
