# Generated by Django 2.2.13 on 2020-07-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0072_phonenumber_sherpa_delivery_percentage'),
        ('sherpa', '0072_prospect_entity_name'),
    ]

    operations = [
    ]
