# Generated by Django 2.2.13 on 2020-07-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0073_merge_20200723_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='entity_name',
        ),
    ]
