# Generated by Django 2.2.13 on 2020-07-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0074_remove_company_skip_opt_out'),
        ('sherpa', '0074_remove_prospect_entity_name'),
    ]

    operations = [
    ]
