# Generated by Django 2.2.12 on 2020-07-24 22:01

from django.db import migrations, models


def set_use_sender_name(apps, schema_editor):
    """
    Override default of True for 'use_sender_name' if 'outgoing_user_names' already set.
    """
    Company = apps.get_model("sherpa", "Company")
    Company.objects.exclude(outgoing_user_names__isnull=True).update(use_sender_name=False)


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0076_auto_20200727_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='use_sender_name',
            field=models.BooleanField(default=True, help_text='Indicate to use sender name when using carrier-approved SMS templates'),
        ),
        migrations.RunPython(set_use_sender_name),

    ]
