# Generated by Django 2.2.12 on 2020-08-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0076_auto_20200727_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadprospects',
            name='existing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadprospects',
            name='new',
            field=models.IntegerField(default=0),
        ),
    ]
