# Generated by Django 2.2.12 on 2020-08-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0077_auto_20200801_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignprospect',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
