# Generated by Django 2.2.12 on 2020-08-03 20:50

from decimal import Decimal
from django.db import migrations, models


def set_skip_trace_price(apps, schema_editor):
    """
    Override default of True for 'use_sender_name' if 'outgoing_user_names' already set.
    """
    Company = apps.get_model("sherpa", "Company")
    SkipTracePrice = apps.get_model("sherpa", "SkipTracePrice")

    for company in Company.objects.all():
        price = SkipTracePrice.objects.filter(company=company).first()
        if price:
            company.skip_trace_price = price.price
            company.save(update_fields=['skip_trace_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0077_auto_20200801_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadskiptrace',
            name='skip_trace_price',
        ),
        migrations.AddField(
            model_name='company',
            name='skip_trace_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.15'), max_digits=3),
        ),
        migrations.RunPython(set_skip_trace_price),
        migrations.DeleteModel(
            name='SkipTracePrice',
        ),
    ]
