# Generated by Django 2.2.13 on 2020-08-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0077_auto_20200801_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsbatch',
            name='error_30003',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statsbatch',
            name='error_30003_att',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statsbatch',
            name='error_30005',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statsbatch',
            name='error_30007',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
