# Generated by Django 2.2.13 on 2020-08-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0078_auto_20200804_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('expired', 'Expired')], max_length=16, null=True),
        ),
    ]
