# Generated by Django 2.2.13 on 2020-08-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0079_auto_20200804_1406'),
        ('sherpa', '0079_auto_20200804_1352'),
    ]

    operations = [
    ]
