# Generated by Django 2.2.13 on 2020-08-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0078_auto_20200803_2315'),
        ('sherpa', '0080_merge_20200804_1434'),
    ]

    operations = [
    ]
