# Generated by Django 2.2.13 on 2020-08-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0081_auto_20200804_1457'),
        ('sherpa', '0081_merge_20200804_1633'),
    ]

    operations = [
    ]
