# Generated by Django 2.2.13 on 2020-08-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0082_merge_20200804_1655'),
        ('sherpa', '0078_auto_20200803_2050'),
    ]

    operations = [
    ]
