# Generated by Django 2.2.13 on 2020-08-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0081_company_record_calls'),
        ('sherpa', '0083_merge_20200804_1656'),
    ]

    operations = [
    ]
