# Generated by Django 2.2.12 on 2020-08-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0084_merge_20200804_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.AlterField(
            model_name='company',
            name='skip_trace_price',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=3),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='skip_trace_price',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=3),
        ),
    ]
