# Generated by Django 2.2.13 on 2020-08-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0077_company_use_sender_name'),
        ('sherpa', '0084_merge_20200804_1658'),
    ]

    operations = [
    ]
