# Generated by Django 2.2.13 on 2020-08-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0085_auto_20200804_1742'),
        ('sherpa', '0085_merge_20200804_1818'),
    ]

    operations = [
    ]
