# Generated by Django 2.2.13 on 2020-08-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0085_merge_20200804_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='skip_trace_price',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=3),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='skip_trace_price',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=3),
        ),
    ]
