# Generated by Django 2.2.13 on 2020-08-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0087_activity_related_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='unread_alert_might_be_stuck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='unread_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
