# Generated by Django 2.2.13 on 2020-08-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0086_merge_20200805_1151'),
        ('sherpa', '0088_auto_20200806_1051'),
    ]

    operations = [
    ]
