# Generated by Django 2.2.13 on 2020-08-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0089_merge_20200806_1057'),
        ('sherpa', '0087_remove_campaign_folder'),
    ]

    operations = [
    ]
