# Generated by Django 2.2.13 on 2020-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0090_merge_20200806_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='unread_alert_might_be_stuck',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='unread_alert_sent',
            field=models.BooleanField(null=True),
        ),
    ]
