# Generated by Django 2.2.13 on 2020-08-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0091_auto_20200808_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwilioResult',
        ),
    ]
