# Generated by Django 2.2.13 on 2020-08-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0092_delete_twilioresult'),
        ('sherpa', '0092_auto_20200811_1129'),
    ]

    operations = [
    ]
