# Generated by Django 2.2.13 on 2020-08-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0093_merge_20200811_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
