# Generated by Django 2.2.13 on 2020-08-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0094_auto_20200811_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_free_beta',
        ),
    ]
