# Generated by Django 2.2.13 on 2020-08-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0095_remove_company_is_free_beta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsbatch',
            name='error_30003',
        ),
        migrations.RemoveField(
            model_name='statsbatch',
            name='error_30003_att',
        ),
        migrations.RemoveField(
            model_name='statsbatch',
            name='error_30005',
        ),
        migrations.RemoveField(
            model_name='statsbatch',
            name='error_30007',
        ),
    ]
