# Generated by Django 2.2.13 on 2020-08-13 12:42

from django.db import migrations


def set_sort_orders(apps, schema_editor):
    """
    Set the sms template sort order based on each company.
    """
    Company = apps.get_model('sherpa', 'Company')

    for company in Company.objects.all():
        templates = company.smstemplate_set.all().order_by('id')
        for i, template in enumerate(templates):
            template.sort_order = i
            template.save(update_fields=['sort_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0096_auto_20200812_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'ordering': ('sort_order',)},
        ),
        migrations.RunPython(set_sort_orders, migrations.RunPython.noop),
    ]
