# Generated by Django 2.2.13 on 2020-08-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0096_auto_20200812_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='affiliate_option_selected',
        ),
        migrations.RemoveField(
            model_name='company',
            name='has_billing_zip',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_affiliate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='show_getting_started_billing',
        ),
        migrations.RemoveField(
            model_name='company',
            name='timezone_confirmed',
        ),
    ]
