# Generated by Django 2.2.13 on 2020-08-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0097_auto_20200813_1242'),
        ('sherpa', '0097_auto_20200813_1512'),
    ]

    operations = [
    ]
