# Generated by Django 2.2.13 on 2020-08-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0098_merge_20200813_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmessage',
            name='unread_alert_might_be_stuck',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='unread_alert_sent',
        ),
    ]
