# Generated by Django 2.2.13 on 2020-08-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0099_auto_20200815_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='check_twilio_phone_balance',
        ),
        migrations.RemoveField(
            model_name='market',
            name='last_sms_delay_sent',
        ),
        migrations.RemoveField(
            model_name='market',
            name='request_status',
        ),
    ]
