# Generated by Django 2.2.13 on 2020-08-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0100_auto_20200817_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastUploadFieldMapping',
        ),
    ]
