# Generated by Django 2.2.13 on 2020-08-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0101_delete_lastuploadfieldmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='cooldown_end_utc',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='cooldown_start_utc',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='deactivated_utc',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='last_received_local',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='last_send_local',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='total_30003_ATT_errors',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='total_30003_errors',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='total_30005_errors',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='total_30007_errors',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='total_other_errors',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='total_received',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='total_received_today',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='twilio_sid_archive',
        ),
    ]
