# Generated by Django 2.2.13 on 2020-08-19 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sherpa', '0102_auto_20200818_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigatorlist',
            name='type',
            field=models.CharField(blank=True, choices=[('Litigator', 'Litigator'), ('Complainer', 'Complainer'), ('Reported', 'Reported')], max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='LitigatorReportQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('handled_on', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_handler', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Prospect')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
