# Generated by Django 2.2.13 on 2020-08-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0103_auto_20200819_1632'),
        ('sherpa', '0103_company_is_demo'),
    ]

    operations = [
    ]
