# Generated by Django 2.2.13 on 2020-08-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0106_auto_20200829_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignprospect',
            name='company',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='custom1',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='custom2',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='custom3',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='mailing_city',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='mailing_state',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='mailing_zip',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='phone_carrier',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='phone_raw',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='phone_type',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='phone_type_checked_datetime',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='property_city',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='property_state',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='property_zip',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='related_record_id',
        ),
    ]
