# Generated by Django 2.2.13 on 2020-08-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0107_auto_20200830_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='access_sms_relay',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='campaign_market_filter',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dashboard_day_filter',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='search_input_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='search_is_priority',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='search_lead_stage_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='search_qualified_leads',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twilio_phone_filter_company_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twilio_phone_filter_market_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twilio_phone_filter_number_status',
        ),
    ]
