# Generated by Django 2.2.13 on 2020-08-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0108_auto_20200830_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='next_billing_date',
        ),
        migrations.AddField(
            model_name='company',
            name='cancellation_discount',
            field=models.BooleanField(default=False, help_text='Determines if the next billing cycle should apply a cancellation discount'),
        ),
        migrations.AddField(
            model_name='company',
            name='cancellation_discount_dt',
            field=models.DateTimeField(blank=True, help_text='The date and time when the discount was used.', null=True),
        ),
        migrations.AddField(
            model_name='subscriptioncancellationrequest',
            name='cancellation_reason',
            field=models.CharField(choices=[('no_leads', 'No Leads'), ('missing_functionality', 'Missing Functionality'), ('pricing', 'Pricing to High'), ('not_using', 'Not Using'), ('competitor', 'Moving to Competitor'), ('pause', 'Pause'), ('other', 'Other')], default='other', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptioncancellationrequest',
            name='discount',
            field=models.BooleanField(default=False, help_text='Requests the cancellation discount on their next billing cycle.'),
        ),
        migrations.AddField(
            model_name='subscriptioncancellationrequest',
            name='new_plan',
            field=models.CharField(blank=True, help_text='The new plan ID that company wishes to downgrade to.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='subscriptioncancellationrequest',
            name='pause',
            field=models.BooleanField(default=False, help_text='Request that the account be paused.'),
        ),
        migrations.AlterField(
            model_name='subscriptioncancellationrequest',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptioncancellationrequest',
            name='cancellation_reason_text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='subscriptioncancellationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted_pending', 'Accepted Pending'), ('saved', 'Saved'), ('rejected', 'Rejected'), ('accepted_complete', 'Complete')], default='pending', max_length=17),
        ),
    ]
