# Generated by Django 2.2.13 on 2020-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0109_auto_20200831_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='alternate_message',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='message',
            field=models.CharField(max_length=320),
        ),
    ]
