# Generated by Django 2.2.13 on 2020-09-02 21:37

from django.db import migrations, models


def load_active_templates(apps, schema_editor):
    Company = apps.get_model('sherpa', 'Company')
    CarrierTemplates = apps.get_model('sms', 'CarrierApprovedTemplate')
    templates = CarrierTemplates.objects.filter(is_active=True).values_list('pk', flat=True)
    for comp in Company.objects.filter(send_carrier_approved_templates=True):
        comp.carrier_templates.add(*templates)

class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_carrierapprovedtemplate_alternate_message'),
        ('sherpa', '0110_auto_20200831_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='carrier_templates',
            field=models.ManyToManyField(help_text='Current subscribed list of CarrierApprovedTemplates.', related_name='carrier_templates', to='sms.CarrierApprovedTemplate'),
        ),
        migrations.RunPython(load_active_templates, migrations.RunPython.noop)
    ]
