# Generated by Django 2.2.13 on 2020-09-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('sherpa', '0110_auto_20200831_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='mailing_address_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_prospects', to='properties.Address'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='property_address_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_prospects', to='properties.Address'),
        ),
    ]
