# Generated by Django 2.2.13 on 2020-09-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0111_auto_20200903_1403'),
        ('sherpa', '0111_company_carrier_templates'),
    ]

    operations = [
    ]
