# Generated by Django 2.2.13 on 2020-09-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0112_merge_20200903_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='carrier_templates',
            field=models.ManyToManyField(help_text='Current subscribed list of CarrierApprovedTemplates.', related_name='carrier_template', to='sms.CarrierApprovedTemplate'),
        ),
    ]
