# Generated by Django 2.2.13 on 2020-09-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0113_auto_20200904_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcode',
            name='is_affiliate_plan',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='monthly_upload_limit',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='option_1_affiliate_monthly_upload_limit',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='option_1_affiliate_plan_signup_description',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='option_1_affiliate_subscription_plan_id',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='option_1_discount_code',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='option_2_affiliate_monthly_upload_limit',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='option_2_affiliate_plan_signup_description',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='option_2_affiliate_subscription_plan_id',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='option_2_discount_code',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='plan_signup_description',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='subscription_plan_id',
        ),
    ]
