# Generated by Django 2.2.13 on 2020-09-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0115_auto_20200908_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardData',
        ),
    ]
