# Generated by Django 2.2.13 on 2020-09-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0116_delete_dashboarddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomingCall',
        ),
    ]
