# Generated by Django 2.2.13 on 2020-09-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property'),
        ('sherpa', '0117_delete_incomingcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
    ]
