# Generated by Django 2.2.13 on 2020-09-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0118_prospect_prop'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_smart_stacker',
            field=models.BooleanField(default=False, help_text='Determines if the company can view Smart Stacker.'),
        ),
    ]
