# Generated by Django 2.2.13 on 2020-09-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0119_company_allow_smart_stacker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skiptraceproperty',
            name='testing_address',
        ),
        migrations.RemoveField(
            model_name='skiptraceproperty',
            name='testing_address_type',
        ),
        migrations.RemoveField(
            model_name='skiptraceproperty',
            name='testing_city',
        ),
        migrations.RemoveField(
            model_name='skiptraceproperty',
            name='testing_first_name',
        ),
        migrations.RemoveField(
            model_name='skiptraceproperty',
            name='testing_last_name',
        ),
        migrations.RemoveField(
            model_name='skiptraceproperty',
            name='testing_state',
        ),
        migrations.RemoveField(
            model_name='skiptraceproperty',
            name='testing_zip',
        ),
    ]
