# Generated by Django 2.2.16 on 2020-09-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0119_company_allow_smart_stacker'),
        ('prospects', '0010_prospecttagassignment'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations = [
                migrations.AlterField(
                    model_name='prospect',
                    name='tags',
                    field=models.ManyToManyField(blank=True, through='prospects.ProspectTagAssignment', to='prospects.ProspectTag'),
                ),
            ],
        ),
    ]
