# Generated by Django 2.2.13 on 2020-09-18 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_optoutlanguage'),
        ('sherpa', '0120_auto_20200914_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sherpa.SMSTemplate'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.SMSTemplateCategory'),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sherpa.Campaign'),
        ),
    ]
