# Generated by Django 2.2.13 on 2020-09-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0120_auto_20200914_2005'),
        ('sherpa', '0120_auto_20200914_2143'),
    ]

    operations = [
    ]
