# Generated by Django 2.2.13 on 2020-09-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0121_auto_20200918_1347'),
        ('sherpa', '0121_merge_20200916_1258'),
    ]

    operations = [
    ]
