# Generated by Django 2.2.13 on 2020-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0122_merge_20200921_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='delivery_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
