# Generated by Django 2.2.13 on 2020-09-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0123_smstemplate_delivery_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='response_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
