# Generated by Django 2.2.13 on 2020-09-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0124_smstemplate_response_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='default_alternate_message',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
