# Generated by Django 2.2.13 on 2020-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0126_userprofile_unread_prospect_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsbatch',
            name='skipped_verizon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignprospect',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('threshold', 'Threshold'), ('has_responded', 'Has responded previously'), ('company_dnc', 'Company DNC'), ('public_dnc', 'Public DNC'), ('litigator', 'Litigator'), ('has_receipt', 'Has SMS Receipt'), ('forced', 'Forced'), ('opt_out_required', 'Opt-out required'), ('carrier_att', 'AT&T'), ('carrier_verizon', 'Verizon'), ('outgoing_not_set', 'Outgoing not set'), ('wrong_number', 'Wrong number')], max_length=16),
        ),
    ]
