# Generated by Django 2.2.16 on 2020-09-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0127_auto_20200925_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statsbatch',
            old_name='skipped_opt_out',
            new_name='skipped_opted_out',
        ),
    ]
