# Generated by Django 2.2.16 on 2020-09-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0128_auto_20200929_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsrelaynumberassignment',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='smsrelaynumberassignment',
            name='twilio_relay_number',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='sms_relay_map',
        ),
        migrations.DeleteModel(
            name='SMSRelayMap',
        ),
        migrations.DeleteModel(
            name='SMSRelayNumber',
        ),
        migrations.DeleteModel(
            name='SMSRelayNumberAssignment',
        ),
    ]
