# Generated by Django 2.2.13 on 2020-10-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0129_auto_20200930_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignprospect',
            name='has_responded_via_call',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='sherpa_phone_number',
        ),
        migrations.RemoveField(
            model_name='campaignprospect',
            name='sherpa_phone_number_status',
        ),
    ]
