# Generated by Django 2.2.13 on 2020-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0129_auto_20200930_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='has_sms_send_received_checked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='is_phone_type_checked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='synced_dnc',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
