# Generated by Django 2.2.13 on 2020-10-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0130_auto_20201011_1029'),
        ('sherpa', '0130_auto_20201007_1519'),
    ]

    operations = [
    ]
