# Generated by Django 2.2.13 on 2020-10-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0131_merge_20201011_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='uuid_token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
