# Generated by Django 2.2.13 on 2020-10-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0133_market_current_spam_cooldown_period_end'),
        ('sherpa', '0133_auto_20201017_1133'),
    ]

    operations = [
    ]
