# Generated by Django 2.2.13 on 2020-10-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0134_merge_20201017_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_type', to='sherpa.PhoneType'),
        ),
    ]
