# Generated by Django 2.2.13 on 2020-10-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0136_auto_20201024_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='followup_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sherpa.Campaign'),
        ),
    ]
