# Generated by Django 2.2.13 on 2020-10-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0137_campaign_followup_from'),
        ('sherpa', '0135_prospect_phone'),
    ]

    operations = [
    ]
