# Generated by Django 2.2.13 on 2020-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0139_auto_20201029_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
