# Generated by Django 2.2.13 on 2020-11-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0140_prospect_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadstage',
            options={},
        ),
        migrations.RenameField(
            model_name='leadstage',
            old_name='order',
            new_name='sort_order',
        ),
    ]
