# Generated by Django 2.2.13 on 2020-11-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0141_auto_20201106_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstage',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
