# Generated by Django 2.2.13 on 2020-11-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0142_auto_20201106_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadstage',
            options={'ordering': ('sort_order',)},
        ),
    ]
