# Generated by Django 2.2.13 on 2020-11-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_upload_skip_trace'),
        ('sherpa', '0143_auto_20201107_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='upload_duplicate',
            field=models.BooleanField(blank=True, help_text="If this was duplicated in two or more Skip Trace uploads, don't charge.", null=True),
        ),
        migrations.AddField(
            model_name='skiptraceproperty',
            name='prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
    ]
