# Generated by Django 2.2.13 on 2020-11-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0144_auto_20201110_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
