# Generated by Django 2.2.13 on 2020-11-19 23:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sherpa', '0145_auto_20201118_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='SherpaTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('task', models.PositiveSmallIntegerField(choices=[(0, 'Prospect Hub Push to Campaign')])),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('metrics', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Queued'), (3, 'Running'), (6, 'Error'), (5, 'Paused'), (4, 'Complete')], default=1)),
                ('pause', models.BooleanField(default=False, help_text='Set to True to pause the task.')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Total amount of times a task has been restarted from an error.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
