# Generated by Django 2.2.13 on 2020-11-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0146_sherpatask'),
        ('sherpa', '0146_campaign_campaign_stats'),
    ]

    operations = [
    ]
