# Generated by Django 2.2.13 on 2020-11-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0147_merge_20201123_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='is_archived',
            field=models.BooleanField(null=True),
        ),
    ]
