# Generated by Django 2.2.13 on 2020-12-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0151_auto_20210114_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='sherpatask',
            name='delay',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
