# Generated by Django 2.2.13 on 2020-12-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0148_prospect_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadprospects',
            name='existing_properties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadprospects',
            name='new_properties',
            field=models.IntegerField(default=0),
        ),
    ]
