# Generated by Django 2.2.13 on 2020-12-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0149_auto_20201216_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unread_prospect_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
