# Generated by Django 2.2.13 on 2020-12-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0149_sherpatask_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sherpatask',
            name='task',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prospect Hub Push to Campaign'), (1, 'Push to Podio')]),
        ),
    ]
