# Generated by Django 2.2.13 on 2021-01-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0150_auto_20201228_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_crm_integration',
            field=models.BooleanField(default=False),
        ),
    ]
