# Generated by Django 2.2.13 on 2021-02-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0151_company_enable_crm_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive'), ('released', 'Released'), ('cooldown', 'Cooldown')], db_index=True, default='active', max_length=16),
        ),
    ]
