# Generated by Django 2.2.13 on 2021-02-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0153_auto_20210215_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_optional_opt_out',
            field=models.BooleanField(default=True, help_text='Used to toggle opt-out language for telephony providers where this is optional.'),
        ),
    ]
