# Generated by Django 2.2.13 on 2021-02-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0152_userprofile_invite_code'),
        ('sherpa', '0153_auto_20210215_1524'),
    ]

    operations = [
    ]
