# Generated by Django 2.2.13 on 2021-02-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0153_auto_20210215_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_direct_mail_integration',
            field=models.BooleanField(default=False),
        ),
    ]
