# Generated by Django 2.2.13 on 2021-02-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0154_merge_20210223_0612'),
        ('sherpa', '0154_auto_20210218_1829'),
    ]

    operations = [
    ]
