# Generated by Django 2.2.13 on 2021-03-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0155_merge_20210223_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sherpatask',
            name='task',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Push to Campaign'), (1, 'Push to Podio')]),
        ),
    ]
