# Generated by Django 2.2.13 on 2021-03-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0157_merge_20210302_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadprospects',
            name='duplicated_prospects',
            field=models.IntegerField(default=0),
        ),
    ]
