# Generated by Django 2.2.13 on 2021-03-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0154_company_enable_optional_opt_out'),
        ('sherpa', '0156_auto_20210302_0424'),
    ]

    operations = [
    ]
