# Generated by Django 2.2.13 on 2021-03-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0157_auto_20210302_1744'),
        ('sherpa', '0157_merge_20210302_2208'),
    ]

    operations = [
    ]
