# Generated by Django 2.2.13 on 2021-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0158_merge_20210302_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignprospect',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignprospect',
            name='last_inbound_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignprospect',
            name='last_outbound_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignprospect',
            name='total_mailings_sent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
