# Generated by Django 2.2.13 on 2021-03-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0157_uploadprospects_duplicated_prospects'),
        ('sherpa', '0158_merge_20210302_2240'),
    ]

    operations = [
    ]
