# Generated by Django 2.2.13 on 2021-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0159_merge_20210309_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadskiptrace',
            name='begin_prop_stack_processing',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadskiptrace',
            name='is_prop_stack_upload',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadskiptrace',
            name='prop_stack_file_ready',
            field=models.NullBooleanField(default=False),
        ),
    ]
