# Generated by Django 2.2.13 on 2021-03-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0159_merge_20210309_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_dm_golden_address',
            field=models.BooleanField(default=True),
        ),
    ]
