# Generated by Django 2.2.13 on 2021-03-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0159_merge_20210309_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigatorreportqueue',
            name='conversation_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='litigatorreportqueue',
            name='reason',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='litigatorreportqueue',
            name='prospect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sherpa.Prospect'),
        ),
    ]
