# Generated by Django 2.2.13 on 2021-03-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0160_company_enable_dm_golden_address'),
        ('sherpa', '0160_auto_20210310_2313'),
    ]

    operations = [
    ]
