# Generated by Django 2.2.13 on 2021-03-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0160_auto_20210322_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigatorreportqueue',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
