# Generated by Django 2.2.13 on 2021-03-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0154_company_enable_direct_mail_integration'),
        ('sherpa', '0161_merge_20210311_1953'),
        ('sherpa', '0159_auto_20210310_0614'),
    ]

    operations = [
    ]
