# Generated by Django 2.2.13 on 2021-03-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0163_campaign_is_direct_mail'),
        ('sherpa', '0161_litigatorreportqueue_phone'),
    ]

    operations = [
    ]
