# Generated by Django 2.2.13 on 2021-03-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0164_merge_20210323_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='enable_direct_mail_integration',
            new_name='allow_direct_mail',
        ),
    ]
