# Generated by Django 2.2.13 on 2021-03-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0165_auto_20210325_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_mail_drop_date_hours', models.IntegerField(default=48)),
            ],
        ),
    ]
