# Generated by Django 2.2.13 on 2021-03-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0166_sitesettings'),
        ('sherpa', '0160_auto_20210325_1632'),
    ]

    operations = [
    ]
