# Generated by Django 2.2.13 on 2021-04-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0167_merge_20210329_1720'),
        ('sherpa', '0161_auto_20210401_2251'),
    ]

    operations = [
    ]
