# Generated by Django 2.2.13 on 2021-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0170_auto_20210408_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='enable_crm_integration',
            field=models.BooleanField(default=True),
        ),
    ]
