# Generated by Django 2.2.13 on 2021-04-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0171_auto_20210416_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='postcard_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.44', max_digits=8),
        ),
    ]
