# Generated by Django 2.2.13 on 2021-04-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0172_company_postcard_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_path', models.FileField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True)),
                ('header_copy', models.CharField(blank=True, max_length=255)),
                ('body_copy', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=255)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('display_amount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeatureNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_tried', models.BooleanField(default=False)),
                ('dismissed_or_tried_dt', models.DateTimeField(blank=True, null=True)),
                ('display_count', models.IntegerField(default=0)),
                ('feature_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sherpa.FeatureNotification')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sherpa.UserProfile')),
            ],
            options={
                'unique_together': {('user_profile', 'feature_notification')},
            },
        ),
    ]
