# Generated by Django 2.2.13 on 2021-04-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0173_featurenotification_userfeaturenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='smarty_streets_nightly_run_count',
            field=models.IntegerField(default=5000000),
        ),
    ]
