# Generated by Django 2.2.13 on 2021-04-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0174_sitesettings_smarty_streets_nightly_run_count'),
        ('sherpa', '0174_auto_20210426_2113'),
    ]

    operations = [
    ]
