# Generated by Django 2.2.13 on 2021-05-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0175_merge_20210429_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadskiptrace',
            name='push_to_campaign_stage',
            field=models.CharField(choices=[('initial', 'Starting'), ('creating_properties', 'Creating properties'), ('pushing_to_campaign', 'Pushing to campaign')], max_length=255, null=True),
        ),
    ]
