# Generated by Django 2.2.23 on 2021-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_auto_20210608_0229'),
        ('skiptrace', '0003_uploadskiptracepropertytag'),
        ('sherpa', '0177_auto_20210526_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadskiptrace',
            name='property_tags',
            field=models.ManyToManyField(blank=True, through='skiptrace.UploadSkipTracePropertyTag', to='properties.PropertyTag'),
        ),
    ]
