# Generated by Django 2.2.23 on 2021-06-30 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0178_uploadskiptrace_property_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignprospect',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sherpa.UserProfile'),
        ),
        migrations.AddField(
            model_name='campaignprospect',
            name='removed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
