# Generated by Django 2.2.24 on 2021-07-19 19:01

from django.db import migrations, models
import phone.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0179_auto_20210630_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=255, null=True, validators=[phone.validators.validate_mobile_or_landline]),
        ),
    ]
