# Generated by Django 2.2.24 on 2021-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0180_auto_20210719_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
