# Generated by Django 2.2.24 on 2021-08-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0181_auto_20210730_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='messaging_provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('telnyx', 'Telnyx'), ('inteliquent', 'Inteliquent')], default='telnyx', max_length=16),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('telnyx', 'Telnyx'), ('inteliquent', 'Inteliquent')], default='telnyx', max_length=16),
        ),
        migrations.AlterField(
            model_name='statsbatch',
            name='provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('telnyx', 'Telnyx'), ('inteliquent', 'Inteliquent')], default='twilio', max_length=16),
        ),
    ]
