# Generated by Django 2.2.24 on 2021-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0182_auto_20210802_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadskiptrace',
            name='push_to_campaign_stage',
            field=models.CharField(blank=True, choices=[('initial', 'Starting'), ('creating_properties', 'Creating properties'), ('pushing_to_campaign', 'Pushing to campaign')], max_length=255, null=True),
        ),
    ]
