# Generated by Django 2.2.24 on 2021-08-23 22:58

from django.db import migrations, models


def update_postcard_price(apps, schema_editor):
    """
    Update postcard price to .48
    """
    Company = apps.get_model("sherpa", "Company")
    Company.objects.update(postcard_price=.48)


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0183_auto_20210820_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postcard_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.48', max_digits=8),
        ),

        migrations.RunPython(update_postcard_price, migrations.RunPython.noop)
    ]
