# Generated by Django 2.2.24 on 2021-08-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpa', '0184_auto_20210823_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(choices=[('Added to DNC', 'Added to DNC'), ('Removed from DNC', 'Removed from DNC'), ('Owner Not Valid', 'Owner Not Valid'), ('Owner Verified', 'Owner Verified'), ('Owner Unverified', 'Owner Unverified'), ('Added as Priority', 'Added as Priority'), ('Removed as Priority', 'Removed as Priority'), ('Qualified Lead Added', 'Qualified Lead Added'), ('Qualified Lead Removed', 'Qualified Lead Removed'), ('Added Autodead', 'Added Autodead'), ('Removed Autodead', 'Removed Autodead'), ('Created Note', 'Created Note'), ('Added Wrong Number', 'Added Wrong Number'), ('Removed Wrong Number', 'Removed Wrong Number'), ('Click to Call', 'Click to Call'), ('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call'), ('General Call', 'General Call')], db_index=True, max_length=255),
        ),
    ]
